from django.contrib.auth.models import AbstractUser
from django.db import models

class UserRole(models.TextChoices):
    ADMIN = 'ADMIN', 'Admin'
    MANAGER = 'MANAGER', 'Manager'
    STAFF = 'STAFF', 'Staff / Cashier'

class User(AbstractUser):
    role = models.CharField(
        max_length=20,
        choices=UserRole.choices,
        default=UserRole.STAFF,
        help_text="Designates the permissions and operational scope of this user."
    )
    phone = models.CharField(max_length=20, blank=True, null=True, help_text="Contact phone number")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-date_joined']
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return f"{self.get_full_name() or self.username} ({self.get_role_display()})"

    @property
    def is_admin_user(self):
        return self.role == UserRole.ADMIN or self.is_superuser

    @property
    def is_manager_user(self):
        return self.role in [UserRole.ADMIN, UserRole.MANAGER] or self.is_superuser

    @property
    def is_staff_user(self):
        return self.is_authenticated

    @property
    def role_badge_class(self):
        badges = {
            UserRole.ADMIN: 'badge-admin',
            UserRole.MANAGER: 'badge-manager',
            UserRole.STAFF: 'badge-staff',
        }
        return badges.get(self.role, 'badge-secondary')


class StoreSetting(models.Model):
    name = models.CharField(
        max_length=150,
        default="StockFlow Supermarket",
        help_text="Name of the supermarket or retail enterprise"
    )
    branch_name = models.CharField(
        max_length=100,
        default="Main Branch",
        help_text="Specific store branch being inventoried"
    )
    phone = models.CharField(max_length=30, blank=True, default="+254 700 123 456")
    email = models.EmailField(blank=True, default="inventory@stockflow.internal")
    address = models.TextField(blank=True, default="Kenyatta Avenue, Nairobi, Kenya")
    tax_pin = models.CharField(max_length=50, blank=True, default="P051234567Z", help_text="KRA PIN or Business Registration Number")
    currency_symbol = models.CharField(max_length=10, default="KES")
    receipt_footer_note = models.TextField(
        blank=True,
        default="Official Inventory Movement Record. Generated by StockFlow Smart Management System."
    )
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Supermarket Store Setting'
        verbose_name_plural = 'Supermarket Store Settings'

    def __str__(self):
        return f"{self.name} - {self.branch_name}"

    @classmethod
    def get_settings(cls):
        setting, _ = cls.objects.get_or_create(id=1)
        return setting
