# Generated by Django 6.0.7 on 2026-09-09 11:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Stock Adjustment')], help_text='Nature of the stock operation', max_length=20)),
                ('quantity', models.PositiveIntegerField(help_text='Units added, removed, or changed', validators=[django.core.validators.MinValueValidator(1)])),
                ('previous_quantity', models.IntegerField(help_text='Inventory count before this operation')),
                ('new_quantity', models.IntegerField(help_text='Inventory count after this operation')),
                ('reason', models.CharField(help_text='Operational justification (e.g. Purchase order, Retail sale, Spoilage, Physical count)', max_length=255)),
                ('reference', models.CharField(blank=True, help_text='Document reference (e.g., PO-4920, INV-1029, AUDIT-2026)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(help_text='Product affected by this inventory operation', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product')),
                ('user', models.ForeignKey(help_text='Staff or manager who authorized/executed this change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
