# Generated by Django 6.0.7 on 2026-09-09 12:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorylocation_alter_product_maximum_stock_and_more'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='destination_location',
            field=models.ForeignKey(blank=True, help_text='Destination location if this is a transfer movement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_movements', to='inventory.inventorylocation'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Specific physical inventory location affected', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventorylocation'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Stock Adjustment'), ('TRANSFER', 'Stock Transfer'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In')], help_text='Nature of the stock operation', max_length=20),
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number of units transferred', validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.CharField(help_text='Transfer justification or requisition note', max_length=255)),
                ('reference', models.CharField(blank=True, help_text='Requisition note or transfer order reference e.g. TR-2026-001', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('destination_location', models.ForeignKey(help_text='Location receiving the inventory', on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='inventory.inventorylocation')),
                ('product', models.ForeignKey(help_text='Product being transferred between inventory locations', on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='inventory.product')),
                ('source_location', models.ForeignKey(help_text='Location dispatching the inventory', on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='inventory.inventorylocation')),
                ('user', models.ForeignKey(help_text='User who authorized or performed the transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_authorized', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Transfer',
                'verbose_name_plural': 'Stock Transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='transfer',
            field=models.ForeignKey(blank=True, help_text='Associated stock transfer if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='stock.stocktransfer'),
        ),
    ]
