# Generated by Django 6.0.7 on 2026-09-10 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_storesetting_created_at_storesetting_owner_user_shop'),
        ('stock', '0002_stockmovement_destination_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Shop or store organization this movement belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='accounts.storesetting'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Shop or store organization this transfer belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='accounts.storesetting'),
        ),
    ]
