# Generated by Django 6.0.7 on 2026-09-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='StockFlow Supermarket', help_text='Name of the supermarket or retail enterprise', max_length=150)),
                ('branch_name', models.CharField(default='Main Branch', help_text='Specific store branch being inventoried', max_length=100)),
                ('phone', models.CharField(blank=True, default='+254 700 123 456', max_length=30)),
                ('email', models.EmailField(blank=True, default='inventory@stockflow.internal', max_length=254)),
                ('address', models.TextField(blank=True, default='Kenyatta Avenue, Nairobi, Kenya')),
                ('tax_pin', models.CharField(blank=True, default='P051234567Z', help_text='KRA PIN or Business Registration Number', max_length=50)),
                ('currency_symbol', models.CharField(default='KES', max_length=10)),
                ('receipt_footer_note', models.TextField(blank=True, default='Official Inventory Movement Record. Generated by StockFlow Smart Management System.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supermarket Store Setting',
                'verbose_name_plural': 'Supermarket Store Settings',
            },
        ),
    ]
