# Generated by Django 6.0.7 on 2026-09-10 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_storesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Primary administrator / owner of this shop', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Shop or store organization this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.storesetting'),
        ),
    ]
