# Generated by Django 6.0.7 on 2026-09-09 12:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Main Store, Back Store, Central Warehouse', max_length=100)),
                ('code', models.CharField(db_index=True, help_text='Short identifier e.g. MAIN, BACK, WH1', max_length=20, unique=True)),
                ('location_type', models.CharField(choices=[('STORE', 'Main Store / Sales Floor'), ('STOCK_ROOM', 'Back Store / Stock Room'), ('WAREHOUSE', 'Warehouse Depot'), ('BRANCH', 'Store Branch'), ('DISTRIBUTION_CENTER', 'Distribution Center')], default='STORE', help_text='Physical nature of this inventory location', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Location details, purpose or notes')),
                ('address', models.TextField(blank=True, help_text='Physical location or shelf section')),
                ('is_active', models.BooleanField(default=True, help_text='Active locations can receive and dispatch stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory Location',
                'verbose_name_plural': 'Inventory Locations',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='maximum_stock',
            field=models.IntegerField(default=100, help_text='Default maximum capacity threshold', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_stock',
            field=models.IntegerField(default=5, help_text='Default low stock alert trigger threshold', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Total in-stock inventory count (summed across all locations)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Physical units in stock at this location', validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_stock', models.IntegerField(default=5, help_text='Low stock alert trigger threshold for this location', validators=[django.core.validators.MinValueValidator(0)])),
                ('maximum_stock', models.IntegerField(default=100, help_text='Maximum capacity threshold for this location', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(help_text='Physical inventory location', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.inventorylocation')),
                ('product', models.ForeignKey(help_text='Product item', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Inventory Stock',
                'verbose_name_plural': 'Inventory Stocks',
                'ordering': ['location__name', 'product__name'],
                'constraints': [models.UniqueConstraint(fields=('product', 'location'), name='unique_product_location')],
            },
        ),
    ]
