# Generated by Django 6.0.7 on 2026-09-10 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_storesetting_created_at_storesetting_owner_user_shop'),
        ('inventory', '0002_inventorylocation_alter_product_maximum_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Shop or store organization this category belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.storesetting'),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Shop or store organization this location belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='accounts.storesetting'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Shop or store organization this product belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.storesetting'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Shop or store organization this supplier belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='accounts.storesetting'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='code',
            field=models.CharField(db_index=True, help_text='Short identifier e.g. MAIN, BACK, WH1', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, help_text='Stock Keeping Unit code', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('shop', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='inventorylocation',
            unique_together={('shop', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('shop', 'sku')},
        ),
    ]
