# Generated by Django 6.0.7 on 2026-09-09 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorylocation_alter_product_maximum_stock_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location where threshold alert occurred', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inventory.inventorylocation'),
        ),
    ]
